# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GeekhakuCli < Formula
  desc "Generates the URL link in various formats"
  homepage "https://github.com/mokupuro/geekhaku-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mokupuro/geekhaku-cli/releases/download/v0.1.3/geekhaku-cli_0.1.3_darwin_arm64.tar.gz"
      sha256 "c14584502e0261e43a8d9dc37da0298d0fde90338580c7ba72d7d11b6ee9752f"

      def install
        bin.install "geekhaku-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mokupuro/geekhaku-cli/releases/download/v0.1.3/geekhaku-cli_0.1.3_darwin_x86_64.tar.gz"
      sha256 "3d3fd51de521d60b4955e193e4318ff3f4ce19f6309c453034b61c65152a8754"

      def install
        bin.install "geekhaku-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mokupuro/geekhaku-cli/releases/download/v0.1.3/geekhaku-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "e028de2abe7f2eaa82c2bea78f038fb372e42feec1b90911c69f6c123121f304"

      def install
        bin.install "geekhaku-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mokupuro/geekhaku-cli/releases/download/v0.1.3/geekhaku-cli_0.1.3_linux_x86_64.tar.gz"
      sha256 "50490c1eb102f327a8738726db2d41c28a6a92db73563f192f5b804e8023161e"

      def install
        bin.install "geekhaku-cli"
      end
    end
  end
end
