# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GeekhakuCli < Formula
  desc "Generates the URL link in various formats"
  homepage "https://github.com/mokupuro/geekhaku-cli"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mokupuro/geekhaku-cli/releases/download/v0.0.8/geekhaku-cli_0.0.8_darwin_arm64.tar.gz"
      sha256 "53fb350b6cb4b332969b510d1f5b82e5bbfff539e83ec1b1830bbcad8a3a2a7c"

      def install
        bin.install "geekhaku-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mokupuro/geekhaku-cli/releases/download/v0.0.8/geekhaku-cli_0.0.8_darwin_x86_64.tar.gz"
      sha256 "8e8d643f39a9b4d02731656c99f57a30640d9cbfc45c8c3173daa7d872781c2e"

      def install
        bin.install "geekhaku-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mokupuro/geekhaku-cli/releases/download/v0.0.8/geekhaku-cli_0.0.8_linux_x86_64.tar.gz"
      sha256 "94245f32a67612ff52fba43c4e85e8bb42c7f0a33111d4f5d41a47460293baef"

      def install
        bin.install "geekhaku-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mokupuro/geekhaku-cli/releases/download/v0.0.8/geekhaku-cli_0.0.8_linux_arm64.tar.gz"
      sha256 "e673d4bbb09120d2f16a14356b79395a4ec1d7c3ce551e6cd5fe771d4da4b5b9"

      def install
        bin.install "geekhaku-cli"
      end
    end
  end
end
